# Generated by Django 5.2.7 on 2026-01-21 03:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('receive_announcements', models.BooleanField(default=True, help_text='Receive org announcements via email')),
                ('receive_events', models.BooleanField(default=True, help_text='Receive event reminders via email')),
                ('receive_finance', models.BooleanField(default=True, help_text='Receive payment confirmations via email')),
                ('receive_applications', models.BooleanField(default=True, help_text='Receive membership updates via email')),
                ('receive_system', models.BooleanField(default=True, help_text='Receive system notifications via email')),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('none', 'No Email')], default='instant', help_text='How often to receive email digests', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_preferences',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
    ]
