# Generated by Django 5.2.7 on 2026-01-18 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_ledgers',
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('members_only', 'Members Only'), ('public_summary', 'Public Summary')], default='members_only', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('web3', 'Web3')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_transactions',
            },
        ),
        migrations.CreateModel(
            name='Web3Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255)),
                ('chain', models.CharField(choices=[('ethereum', 'Ethereum'), ('polygon', 'Polygon'), ('bsc', 'BSC'), ('other', 'Other')], default='other', max_length=20)),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('token_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web3_payments',
            },
        ),
    ]
