# Generated by Django 5.2.7 on 2026-01-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web3payment',
            name='amount_wei',
            field=models.CharField(blank=True, help_text='Amount in Wei (string)', max_length=78),
        ),
        migrations.AddField(
            model_name='web3payment',
            name='contract_address',
            field=models.CharField(blank=True, help_text='SimaorkaDues contract address', max_length=42),
        ),
        migrations.AddField(
            model_name='web3payment',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason if verification failed'),
        ),
        migrations.AddField(
            model_name='web3payment',
            name='org_numeric_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Numeric org ID for smart contract', null=True),
        ),
        migrations.AddField(
            model_name='web3payment',
            name='verification_data',
            field=models.JSONField(blank=True, help_text='Raw verification response from RPC', null=True),
        ),
        migrations.AlterField(
            model_name='web3payment',
            name='amount',
            field=models.DecimalField(decimal_places=18, help_text='Amount in ETH', max_digits=18),
        ),
        migrations.AlterField(
            model_name='web3payment',
            name='chain',
            field=models.CharField(choices=[('ethereum', 'Ethereum'), ('sepolia', 'Sepolia Testnet'), ('polygon', 'Polygon'), ('bsc', 'BSC'), ('other', 'Other')], default='sepolia', max_length=20),
        ),
        migrations.AlterField(
            model_name='web3payment',
            name='token_symbol',
            field=models.CharField(default='ETH', max_length=20),
        ),
        migrations.AlterField(
            model_name='web3payment',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=66, unique=True),
        ),
        migrations.AlterField(
            model_name='web3payment',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
