# Generated by Django 5.2.7 on 2026-01-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='finance_transparency',
            field=models.CharField(choices=[('private', 'Private - Members Only'), ('summary', 'Public Summary'), ('full', 'Full Transparency')], default='private', help_text='Level of financial data visibility to public', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_transparency_note',
            field=models.TextField(blank=True, help_text='Note to display on public finance page'),
        ),
    ]
